name: Unit tests
on: [pull_request]
jobs:
    run-tests:
        name: PHP ${{ matrix.php }} (${{ matrix.os }}, composer ${{ matric.composer-flag }})

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                php: [ 7.2, 7.3, 7.4, 8.0 ]
                os: [ ubuntu-latest ]
                include:
                    -   os: [ ubuntu-latest ]
                        php: 8.1
                        composer-flag: "'--ignore-platform-reqs'"

                    -   os: [ ubuntu-latest ]
                        php: 7.1
                        composer-flag: "'--prefer-lowest'"

        steps:
            -   uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Install dependencies
                run: composer update --prefer-dist ${{ matrix.composer-flag }}

            -   name: PHPUnit tests
                run: ./vendor/bin/phpunit

